# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/predict/?address=0x9D6dB6382444b70a51307A4291188f60D4EEF205&platform=BNB
Accept: application/json

###

